apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "autotls-controller.serviceAccountName" . }}
  labels:
    {{- include "autotls-controller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "autotls-controller.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "autotls-controller.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
