{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "autotls-controller.serviceAccountName" . }}
  labels:
    {{- include "autotls-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs:
      - get
      - watch
      - list
      - patch
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["create"]
{{- end }}
